name: contentatomizer.com
favicon: null
layout_spectrum: 0.21728707943111658
typography_spectrum: 0.5139252480585128
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8479372337460518
  lightness: 0.3847788870334625
  saturation: 0.05869283457286656
  rhythmicContrast: 0.46383104659616947
purpose: []
